Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.


In [3]:
import numpy as np


In [5]:
array_1d = np.arange(1, 11)


In [7]:
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
array_2x5 = array_1d.reshape(2, 5)
print(array_2x5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Exercise 2: Extracting Elements (Index 5 to 15)


In [16]:
import numpy as np

values = np.arange(1, 21)

extracted_elements = values[5:15]

print(extracted_elements)



[ 6  7  8  9 10 11 12 13 14 15]


In [18]:
import pandas as pd 

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

fruit_series['pears'] = 4  

print(fruit_series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [21]:
import pandas as pd  # Import pandas library

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 35, 40, 28, 32, 27, 45, 50],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}

df = pd.DataFrame(data)

print(df)


      name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   22      M
3    David   35      M
4      Eve   40      F
5    Frank   28      M
6    Grace   32      F
7   Hannah   27      F
8      Ian   45      M
9     Jack   50      M


Exercise 5: (Score : 1)
Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


In [24]:
import pandas as pd  # Import pandas library

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 35, 40, 28, 32, 27, 45, 50],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}

df = pd.DataFrame(data)

occupations = ['Programmer', 'Manager', 'Analyst'] * (len(df) // 3) + ['Programmer'] 
df['occupation'] = occupations

print(df)


      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4      Eve   40      F     Manager
5    Frank   28      M     Analyst
6    Grace   32      F  Programmer
7   Hannah   27      F     Manager
8      Ian   45      M     Analyst
9     Jack   50      M  Programmer


Exercise 6: (Score : 1)
Select the rows of the dataframe where the age is greater than or equal to 30.


In [29]:
import pandas as pd  

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 35, 40, 28, 32, 27, 45, 50],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                   'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
}

df = pd.DataFrame(data)

df_filtered = df[df['age'] >= 30]

print(df_filtered)


    name  age gender  occupation
1    Bob   30      M     Manager
3  David   35      M  Programmer
4    Eve   40      F     Manager
6  Grace   32      F  Programmer
8    Ian   45      M     Analyst
9   Jack   50      M  Programmer


Exercise 7: (Score : 2)
Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [32]:
import pandas as pd  # Import pandas library

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 35, 40, 28, 32, 27, 45, 50],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                   'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
}

df = pd.DataFrame(data)

csv_filename = "data.csv"
df.to_csv(csv_filename, index=False)  

df_read = pd.read_csv(csv_filename)

print("Data read from CSV file:")
print(df_read)


Data read from CSV file:
      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4      Eve   40      F     Manager
5    Frank   28      M     Analyst
6    Grace   32      F  Programmer
7   Hannah   27      F     Manager
8      Ian   45      M     Analyst
9     Jack   50      M  Programmer
